/*
 * This can be and is usually generated by
 * `cargo new <project_name> --lib`,
*/

// Inline, within curly brackets
mod front_of_house {
    pub mod hosting {
        pub fn add_to_waitlist() {}

        pub fn seat_at_table() {}
    }

    mod serving {
        fn take_order() {}

        fn serve_order() {}

        fn take_payment() {}
    }
}

mod back_of_house {
    pub struct Breakfast {
        pub toast: String,
        seasonal_fruit: String,
    }

    impl Breakfast {
        pub fn summer(toast: &str) -> Breakfast {
            Breakfast {
                toast: String::from("toast"),
                seasonal_fruit: String::from("peaches"),
            }
        }
    }

    // In contrast, if we make an enum public, all of its variants are then public.
    pub enum Appetizer {
        Soup,
        Salad,
    }

    fn fix_incorrect_order() {
        cook_order();

        // Construct relative paths that begin with parent modules by using `super`
        super::deliver_order();
    }

    fn cook_order() {}
}

// Bring paths into scope
use crate::front_of_house::hosting; // We can now use `hosting::add_to_waitlist` instead of `front_of_house::hosting::add_to_waitlist`
// Providing new names
use crate::front_of_house::hosting as hosting_alias;

pub fn eat_at_restaurant() {
    hosting::seat_at_table(); // since we brought `hosting` into scope via `use` keyword
    hosting_alias::seat_at_table();

    // Absolute path
    crate::front_of_house::hosting::add_to_waitlist();

    // Relative path
    front_of_house::hosting::seat_at_table();

    let mut meal = back_of_house::Breakfast::summer("rye");
    meal.toast = String::from("wheat");
    println!("I'm having {} toast for breakfast!", meal.toast);

    // meal.seasonal_fruit = String::from("blueberries"); // ! ❌ error: `seasonal_fruit` is private

    let order1 = back_of_house::Appetizer::Soup;
    let order2 = back_of_house::Appetizer::Salad;
}

pub fn deliver_order() {}
